export const ErrorCodes = {
  STOCK_CODE_EXISTS: "STOCK_CODE_EXISTS",
  DUPLICATE_CODE: "DUPLICATE_CODE",
  DUPLICATE_INVOICE_NUMBER: "DUPLICATE_INVOICE_NUMBER",
  INVALID_INPUT: "INVALID_INPUT",
  NOT_FOUND: "NOT_FOUND",
  PERIOD_NOT_FOUND: "PERIOD_NOT_FOUND",
  PERIOD_NOT_ACTIVE: "PERIOD_NOT_ACTIVE",
  PERIOD_OVERLAP: "PERIOD_OVERLAP",
  PERIOD_ACTIVE_EXISTS: "PERIOD_ACTIVE_EXISTS",
  PERIOD_CLOSED_READONLY: "PERIOD_CLOSED_READONLY",
  INVALID_PERIOD_RANGE: "INVALID_PERIOD_RANGE",
  NEXT_ACTIVE_PERIOD_REQUIRED: "NEXT_ACTIVE_PERIOD_REQUIRED",
  WORKSPACE_NOT_FOUND: "WORKSPACE_NOT_FOUND",
  NO_WORKSPACES: "NO_WORKSPACES",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export class AppError extends Error {
  code: string;

  constructor(message: string, code: string) {
    super(message);
    this.code = code;
    this.name = "AppError";
  }
}
